
package Client;

import Communication.CClient;
import Communication.Message;
import Communication.MessageCodes;
import Configurations.DefaultConfigs;
import javax.swing.SpinnerNumberModel;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 * Client graphical interface.
 * @author Rafael Sá (104552), Luís Laranjeira (81526)
 */
public class Client_GUI extends javax.swing.JFrame {

    /** Client to receive the reply messages. */
    private final Client client;
    /** Communication client. */
    private CClient cclient;
    /** Request counter. */
    private static int REQUEST_COUNTER;
    /** Client ID. */
    private final int clientId;
    
    /**
     * Creates new form GUI_Client.
     * @param clientID client id
     * @param hostname load balancer host name
     * @param lbPort load balancer port
     */
    public Client_GUI(int clientID, String hostname, int lbPort) {
        initComponents();
        jSpinnerInteractionsCount.setModel(new SpinnerNumberModel(DefaultConfigs.NUMBER_ITERATIONS, 1, Integer.MAX_VALUE, 1));
        initConnection(hostname, lbPort);
        REQUEST_COUNTER = 1000 * clientID;
        this.clientId = clientID;
        this.client = new Client(cclient, this);
        client.start();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitle = new javax.swing.JLabel();
        jButtonEnd = new javax.swing.JButton();
        jSpinnerInteractionsCount = new javax.swing.JSpinner();
        jLabelIterations = new javax.swing.JLabel();
        jButtonRequest = new javax.swing.JButton();
        jTabbedPane = new javax.swing.JTabbedPane();
        jScrollPaneExecuted = new javax.swing.JScrollPane();
        jTableExecutedRequests = new javax.swing.JTable();
        jScrollPanePending = new javax.swing.JScrollPane();
        jTablePendingRequests = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelTitle.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelTitle.setText("Client");
        jLabelTitle.setMaximumSize(new java.awt.Dimension(70, 22));

        jButtonEnd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonEnd.setText("End");
        jButtonEnd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEndActionPerformed(evt);
            }
        });

        jSpinnerInteractionsCount.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jSpinnerInteractionsCount.setMinimumSize(new java.awt.Dimension(50, 24));
        jSpinnerInteractionsCount.setPreferredSize(new java.awt.Dimension(50, 24));

        jLabelIterations.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelIterations.setText("Nº of Iterations:");

        jButtonRequest.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonRequest.setText("New Request");
        jButtonRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRequestActionPerformed(evt);
            }
        });

        jTableExecutedRequests.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Request", "Nº of Iterations", "Reply"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPaneExecuted.setViewportView(jTableExecutedRequests);

        jTabbedPane.addTab("Executed Requests", jScrollPaneExecuted);

        jTablePendingRequests.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Request", "Nº of Iterations"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPanePending.setViewportView(jTablePendingRequests);

        jTabbedPane.addTab("Pending Requests", jScrollPanePending);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jLabelIterations)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jSpinnerInteractionsCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonRequest)
                                .addGap(0, 44, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonEnd)
                                .addGap(8, 8, 8))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonEnd)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinnerInteractionsCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelIterations)
                    .addComponent(jButtonRequest))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * End button action.
     * @param evt event
     */
    private void jButtonEndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEndActionPerformed
        this.cclient.closeConnection();
        System.exit(0);
    }//GEN-LAST:event_jButtonEndActionPerformed

    /**
     * New Request button action.
     * @param evt event
     */
    private void jButtonRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRequestActionPerformed
        try {
            Request request = new Request(++REQUEST_COUNTER, (int)jSpinnerInteractionsCount.getValue());
            Message msg = new Message(true, clientId, request.getId(), MessageCodes.REQUEST, request.getnIterations());
            cclient.sendMessage(msg);
            addPendingRequest(request);
        } catch (NumberFormatException ex) {
            System.out.println(ex.toString());
        }
    }//GEN-LAST:event_jButtonRequestActionPerformed

    /**
     * Connect to the server (load balancer).
     * @param hostname load balancer host name
     * @param port load balancer port
     */
    private void initConnection(String hostname, int port){
        cclient = new CClient(hostname, port);
        cclient.connectToServer();
    }

    /**
     * Add new pending request to GUI.
     * @param request new request
     */
    private void addPendingRequest(Request request){
        DefaultTableModel model;
        model = (DefaultTableModel) jTablePendingRequests.getModel();
        model.addRow(new Object[]{"Request " + request.getId(), request.getnIterations()});
    }

    /**
     * Request completion.
     * Remove from pending requests and adds to executed requests.
     * @param request completed request
     */
    public void newExecutedRequest(Request request){
        if (!SwingUtilities.isEventDispatchThread()) {
            SwingUtilities.invokeLater(() -> {
                newExecutedRequest(request);
            });
            return;
        }
        DefaultTableModel model;
        model = (DefaultTableModel) jTablePendingRequests.getModel();
        for (int i = 0; i < model.getRowCount(); i++) {
            if (((String)model.getValueAt(i, 0)).equals("Request " + request.getId())) {
                model.removeRow(i);
            }
        }
        model = (DefaultTableModel) jTableExecutedRequests.getModel();
        model.addRow(new Object[]{"Request " + request.getId(), request.getnIterations(),request.getReply()});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEnd;
    private javax.swing.JButton jButtonRequest;
    private javax.swing.JLabel jLabelIterations;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JScrollPane jScrollPaneExecuted;
    private javax.swing.JScrollPane jScrollPanePending;
    private javax.swing.JSpinner jSpinnerInteractionsCount;
    private javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JTable jTableExecutedRequests;
    private javax.swing.JTable jTablePendingRequests;
    // End of variables declaration//GEN-END:variables
}
